### PR TITLE
Fixing SSL certificate issue 

### PR DESCRIPTION
**Pull request by mohammedbahja**
https://github.com/policycompass/policycompass/issues/513
policycompass/policycompass-fcmmanager/pull/29

### CODE REVIEW

**Comment by mohammedbahja** [comment]
@FabiApfelkern The issues was related to SSL certificate. 
As you can see, I have committed the web.xml file. If you want to update it manuly, replace http by https.

`<env-entry> 
<env-entry-name>adhocracy.api</env-entry-name>
<env-entry-type>java.lang.String</env-entry-type>
<env-entry-value>https://adhocracy-frontend-stage.policycompass.eu/api/</env-entry-value> 
</env-entry>
<env-entry> 
<env-entry-name>adhocracy.god</env-entry-name>
<env-entry-type>java.lang.String</env-entry-type>
<env-entry-value>https://adhocracy-frontend-stage.policycompass.eu/api/principals/groups/gods/</env-entry-value> 
</env-entry>`

**Comment by FabiApfelkern** [comment]
@mohammedbahja Can you check again?

**Comment by mohammedbahja** [comment]
@FabiApfelkern, I have tested the code on two different local machines and it works well.  I don't know why it is not working on the staging server. I have updated the FCMModels.java to display full error msg, please see the pull request below. 
policycompass/policycompass-fcmmanager/pull/31
Also, may i know the environment staging server os and Java version?

**Comment by FabiApfelkern** [comment]
I redeployed the entire FCM-Manager backend. Maybe it is working now. I have the feeling something is not working correctly with the CI server. We are using Ubuntu 14.04 and Java 1.7.0_95.

**Comment by mohammedbahja** [comment]
@FabiApfelkern thanks, Yes it works now. However, it needs some little enhancement such as the error msgs. BTW, did you do anything difference when you redeployed the code ? Did you restart the tomcat ?

**Pull request merged**
