### PR TITLE
Sprint 3 Development

### PR DESCRIPTION
**Pull request by belalakbar**
…licycompass/policycompass#151 /policycompass/policycompass#150 /policycompass/policycompass#149 /policycompass/policycompass#145 /policycompass/policycompass#141 /policycompass/policycompass#130

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
There is no title, no description and conflicts. This cannot be merged.

**Comment by belalakbar** [comment]
i try to resolve this issue by the given command line but it denied

**Comment by FabiApfelkern** [comment]
Which command line? The one on this page? If you do those command you will run into merge conflicts which you have to resolve. Thats the whole point.

**Comment by belalakbar** [comment]
yes command line, ok can you please bit explain about conflict and guide me how to resolve it

**Pull request closed without merging**
