### PR TITLE
weight calculation using Weka library

### PR DESCRIPTION
**Pull request by mohammedbahja**
policycompass/policycompass/issues/597

### CODE REVIEW

**Comment by mohammedbahja** [comment]
The image below shows the output of weight values generated by weka library. 


To understand how this works, please go through the word document in the attachment first. This has been done by @aquinas9. As you can see, the document explain how to convert the real numbers of the historical data to a fuzzy values. To implement the fuzzy values converter, I have followed the logic in the excel sheet in the attachment. 

Below, is an example of the input of weka library.  


For this example we have three sources and one sink. 
The sources are:
@attribute speed_public_service numeric and the values for this sources is the first column
0.6
0.6 
0.6 
0.4 
0.8
1 
@attribute accessibility numeric
0.2
0.4
0.4
0.6
1
1
@attribute regional_Gdp numeric
0.6
0.6
0.8
0.8
1
1

Then we have the sink 
@attribute 'level of satisfaction' numeric
0.2 
0.2
0.2
0.4
0.8
1

Weka will provide three weights values for the three relationship as shown below. 
1- @attribute speed_public_service numeric --------> @attribute 'level of satisfaction' numeric = 0.31941173668666434
2- @attribute accessibility numeric --------> @attribute 'level of satisfaction' numeric = 0.528144050164785
3- @attribute regional_Gdp numeric--------> @attribute 'level of satisfaction' numeric = 0.25333634551533424


The image below shows an output for deferent example via the IDE



This output will be sent to the front-end via the API /api/v1/fcmmanager/wekaoutput
I hope this explanation is clear. 


Attachments 
[PolicyCompass fuzzy value.xlsx](https://github.com/policycompass/policycompass-fcmmanager/files/319088/PolicyCompass.fuzzy.value.xlsx)

[The details of weka.docx](https://github.com/policycompass/policycompass-fcmmanager/files/319083/The.details.of.weka.docx)

**Comment by mohammedbahja** [comment]
For weka integration and server deployment, I have added the following code to the dependencies of pom.xml 

  ```
<dependency>
        <groupId>nz.ac.waikato.cms.weka</groupId>
        <artifactId>weka-stable</artifactId>
        <version>3.8.0</version>
    </dependency>
```

I think there is no need to import the weka.jar on the server as it should be installed from maven repository as I added dependency in pom.xml.

I am not sure if maven will update the new dependency automatically or not. If not please run this command. 
`mvn clean install -U`

**Comment by FabiApfelkern** [comment]
@mohammedbahja I merged and deployed it on stage. Please check it out!

**Comment by mohammedbahja** [comment]
@FabiApfelkern Many thanks, I am checking it now. seems there are some issues with the server deployment.

**Comment by FabiApfelkern** [comment]
some issues?

**Comment by mohammedbahja** [comment]
It is getting 404 (page not found) when posting on below url.
[https://fcm-stage.policycompass.eu/api/v1/fcmmanager/wekaoutput](url)


I have updated the code to get root cause,I think there is exception on server side.



Please merge the PR below 
policycompass/policycompass-fcmmanager/pull/38

**Comment by mohammedbahja** [comment]
@FabiApfelkern also, I think weka library is not updated from maven repository, because not getting response from method 'wekaOutput'. Required to run command below to sync repository
`mvn clean install -U`

**Pull request merged**
