### PR TITLE
Sprint 3 Development 

### PR DESCRIPTION
**Pull request by belalakbar**
All the following issues has been resolved.
policycompass/policycompass#151
policycompass/policycompass#130

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
I cannot build this branch. It fails with the following error:

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/fki/Dev/policycompass/policycompass-fcmmanager/src/main/java/policycompass/fcmmanager/simulation/pcjfcm.java:[149,65] cannot find symbol
  symbol:   method setValue(double)
  location: class policycompass.fcmmanager.models.FCMConcept
[ERROR] /home/fki/Dev/policycompass/policycompass-fcmmanager/src/main/java/policycompass/fcmmanager/simulation/pcjfcm.java:[150,65] cannot find symbol
  symbol:   method setMetric_id(int)
  location: class policycompass.fcmmanager.models.FCMConcept
[ERROR] /home/fki/Dev/policycompass/policycompass-fcmmanager/src/main/java/policycompass/fcmmanager/simulation/pcjfcm.java:[241,60] cannot find symbol
  symbol:   method setWeight(java.lang.String)
  location: class policycompass.fcmmanager.models.FCMConnection
[INFO] 3 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.817 s
[INFO] Finished at: 2015-08-12T09:52:42+02:00
[INFO] Final Memory: 15M/241M

```

**Comment by belalakbar** [comment]
@FabiApfelkern fixed this error, now compile.

**Comment by FabiApfelkern** [comment]
The usual question: Do I need to reset the database?

**Comment by belalakbar** [comment]
No, Actually I again commit this branch the three files was not copied properly. I made changes on four files.

**Comment by belalakbar** [comment]
You can see the two commits. But in files changes, it show only one, Should I re-create the pull request?

**Comment by FabiApfelkern** [comment]
I don't understand really. What was not copied properly? If you changed 4 files there should be 4 files here.

**Comment by belalakbar** [comment]
Ok I think should again create new pull request then let you know.

**Comment by FabiApfelkern** [comment]
You dont have to create a new pull request. just update the branch

**Comment by belalakbar** [comment]
I updated the branch, now you will try to merge it

**Comment by FabiApfelkern** [comment]
So only one file is change now. Is this correct?

**Comment by belalakbar** [comment]
now every thing is up to date and now you can merge it with the master.

**Comment by FabiApfelkern** [comment]
Can you please answer my question. You have finished 8 issues with changing one file?

**Comment by belalakbar** [comment]
Now read carefully, what I am saying from yesterday. I did two commits in this branch as you suggested (update the branch).
After second commit, it should be display changes in four files. see these changes:
Commit-1 No. of lines 81: 
https://github.com/policycompass/policycompass-fcmmanager/blob/d18909fd6974ae934addd28c7b267e5f7b0dea1d/src/main/java/policycompass/fcmmanager/models/FCMConnection.java
Commit-2 No. of lines 89:
https://github.com/policycompass/policycompass-fcmmanager/blob/9922ba3698d7377f9eb789fff085171f2d8701c8/src/main/java/policycompass/fcmmanager/models/FCMConnection.java

same thing in other files as well. Which I talked about four files changing that is the difference between commit-1 and commit-2 not with master. 

Secondly your question is 8 issues solved with change one file, the clear answer is yes.
These issues solved with changing in both frontend and fcmmanager repositry. If you are still confuesd, then deploy this and check the issue one by one see the results.

I think now you are satisfy with my answer and please update this on live server.

**Comment by belalakbar** [comment]
HI fabian, I got the point on this Pull request which is making you confused. I try to explain here
actually this PR only dealing with the Issue number 151 however I put other number of issues which is making you confused. was it point or something different?

issue #130  from sprint two is already working properly on live 
the issue #130 was 
"The fixed value tab will be removed and new function will be added in the algorithm, which automatically detects the fixed value. The advance setting for activator function will be provided."

 now if you see the stage in run simulation tab there is no fixed value tab (which was there before issue 130 further the advance setting tab was not there before, however it is done under issue number 130.)
 both of these task can been seen on stage, which means that issue 130 is already merged with master and this issue should be closed.

**Pull request merged**
