### PR TITLE
Weka testing on the server 

### PR DESCRIPTION
**Pull request by mohammedbahja**
policycompass/policycompassc#597

### CODE REVIEW

**Comment by mohammedbahja** [comment]
@FabiApfelkern , after merging this,  I will check the following url: [https://fcm-stage.policycompass.eu/api/v1/fcmmanager/wekaoutputtest](url)

If weka library is working on server, It will show output like the screenshot  below.

**Comment by FabiApfelkern** [comment]
@mohammedbahja I have no idea what is going wrong. I did the mvn clean install and rebooted the server. If the dependency is missing, it wouldn't compile. So it must be something different. @slomo Can you help?

**Comment by mohammedbahja** [comment]
@FabiApfelkern, This is  right, if compiled then it means local has been updated from central repository. But the url below should respond
https://fcm-stage.policycompass.eu/api/v1/fcmmanager/wekaoutputtest
Hmmm, can I ask to check this url on the server please ?

**Comment by mohammedbahja** [comment]
@FabiApfelkern @slomo I hope if you could find a time to help me in this.

**Comment by FabiApfelkern** [comment]
@mohammedbahja I have no idea anymore. I'm waiting for @slomo to respond.

**Comment by slomo** [comment]
If I am running 
```
policycompass@poco-test:~/policycompass/policycompass-fcmmanager$ unzip -t \$\{CATALINA_HOME\}/webapps/api.war  | grep weka
```
it returns
```
WEB-INF/lib/weka-stable-3.8.0.jar
```
So it is definitely compiled in.

**Comment by slomo** [comment]
It now works. Due to an error in pom.xml the api.war was deplyoed to the wrong folder.

**Comment by mohammedbahja** [comment]
@slomo Many thanks, this is helpful. May I ask what was the error in pom.xml?

**Comment by slomo** [comment]
I opend a pull request #40

**Pull request merged**
