### PR TITLE
Enabled CORS

### PR DESCRIPTION
**Pull request by FabiApfelkern**
We need CORS support for local development without installing all services. I tested it on the alpha server already.

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
@nrchaudhry Can you please reviews this request? Thanks!

**Comment by nrchaudhry** [comment]
@FabiApfelkern I will done this task until 20th March. Actually, I am currently working on restructuring of FCM Editor.

**Comment by FabiApfelkern** [comment]
But I have already done it. This is a pull request, You just have to check the code and merge it, if it is ok.

**Comment by nrchaudhry** [comment]
Thanks @FabiApfelkern actually I made changes in Database schema and when the database schema will be finalize then I can be able to push back with new changes.

**Comment by FabiApfelkern** [comment]
Probably there is a misunderstanding about Pull Requests. I have changed something on your code. In this case just the web.xml. And you are supposed to review it and if it is ok click on the big green button "Merge pull request". You can just review the few line here. Click on "Files changed". This has nothing to do with you current work on the database. So there is no reason to wait for your changes.

**Comment by nrchaudhry** [comment]
@FabiApfelkern I got your point. Yes it is ok.

Done

**Pull request merged**
